---
title: "eds223_week5_discussion"
format: html
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(sf)
library(terra)
library(spData)
library(spDataLarge)
library(tmap)
```

```{r}
# Load raster data representing grain sizes with the three classes clay, silt and sand
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```

```{r}
nz_height3100 <- nz_height %>%
  dplyr::filter(elevation > 3100) 

template_raster <- rast(resolution = c(3000,3000),# could just use res = 3000 bc cells
crs = crs(nz_height3100), ext(nz_height3100))# rasters are squared anyway

```

```{r}
nz_raster <- rasterize(nz_height3100, template_raster,
                       field = "elevation",
                       fun = length) 

plot(nz_raster, main = "Number of Elevation Points > 3100 in Each Grid Cell")
plot(st_geometry(nz_height3100), add = TRUE)
```

```{r}
# function "max" returns maximum elevation value per cell
nz_raster2 <- rasterize(nz_height3100, template_raster,
                        field = "elevation", 
                        fun = max)

plot(nz_raster2, main = "Maximum Elevation in Each Grid Cell ")
plot(st_geometry(nz_height3100), add = TRUE)
```

```{r}
# Reduce the resolution by combining 2 cells in each direction into larger cells
# Sum the values of all cells for the resulting elevation value
nz_raster_low <- aggregate(nz_raster, fact = 2, fun = sum, na.rm = TRUE)

# Convert the new raster's resolution back to the 3kmx3km resolution of original raster
nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 6 x 6 km", "Resample 6 x 6 km")
plot(plots, main = labs)
```


